name: '🏗️ Build jellyfin-ffmpeg'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  # push:
  #   branches:
  #     - jellyfin
  #   paths-ignore:
  #     - '**/*.md'

  # pull_request:
  #   branches:
  #     - jellyfin
  #   paths-ignore:
  #     - '**/*.md'

  workflow_dispatch:

jobs:
  build_debian:
    uses: ./.github/workflows/_meta.yaml
    with:
      distro: 'debian'
      codenames: '["trixie"]'
      architectures: '["arm64"]'
      release: false
