name: '🚀 Build and Publish jellyfin-ffmpeg'

on:
  release:
    types:
      - released

jobs:
  build_publish_debian:
    uses: ./.github/workflows/_meta.yaml
    with:
      distro: 'debian'
      codenames: '["trixie"]'
      architectures: '["arm64"]'
      release: true
